config:
  timezone: "US/Eastern"
  webhook:
  - "https://maker.ifttt.com/trigger/MY_IFTTT_EVENT_NAME/with/key/*****?value1="
  morningbus:
    bus_check: "MYSCHOOL PS </td><td>9999"
    start: "7:30"
    stop: "8:30"
  afternoonbus:
    bus_check: "MYSCHOOL PS </td><td>9999"
    start: "15:00"
    stop: "16:30"
